#生产环境
server:
  port: 80
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://49.234.96.50:3306/blog?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC&characterEncoding=utf-8&useAffectedRows=true
    username: root
    password: root
   #JPA简化了数据库所有操作
  jpa:
    hibernate:
      ddl-auto: none   #待实体类确定下来后改为none停止更新
    show-sql: true    #输出


  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 500MB

  #日志配置
logging:
  level:    #debug为所有都一个级别
    root: warn
    com.lxd: info
  file:           #日志输出
    path: log/blog-pro.log


  #mybatis
mybatis:
  mapper-locations: classpath:mappers/*.xml  #注意：一定要对应mapper映射xml文件的所在路径
  type-aliases-package: com.lxd.po