#生产环境
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/blog?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC&characterEncoding=utf-8
    username: root
    password: root
   #JPA简化了数据库所有操作
  jpa:
    hibernate:
      ddl-auto: none   #待实体类确定下来后改为none停止更新
    show-sql: true    #输出

  #日志配置
logging:
  level:    #debug为所有都一个级别
    root: warn
    com.lxd: info
  file:           #日志输出
    path: log/blog-pro.log
server:     # 开发环境使用8080端口
  port: 8081